---
# deploy.yml

- hosts: ksql
  user: root

  tasks:
    - name: rebuild project
      local_action: shell mvn clean package chdir=/Users/alexwoolford/ksql-udf-geo
      run_once: True

    - name: stop ksqldb
      service: name=confluent-ksqldb
        state=stopped

    - name: copy jar to ksql instances
      copy:
        src: /Users/alexwoolford/ksql-udf-geo/target/ksql-udf-geo-1.0-SNAPSHOT-jar-with-dependencies.jar
        dest: /opt/ksql-extension/
        owner: cp-ksql
        group: confluent
        mode: 0755
        force: yes

    - name: start ksqldb
      service: name=confluent-ksqldb
        state=started
